#!/bin/bash

# Tests WASI syscalls via C test programs and wasi-libc

make -k clean all

declare -a tests_failed=()

./align__.minimal.out || tests_failed+=("align::*")
./block__.minimal.out || tests_failed+=("block::*")
./block__break-inner.minimal.out || tests_failed+=("block::break-inner")
./br__.minimal.out || tests_failed+=("br::*")
./br__as-binary-both.minimal.out || tests_failed+=("br::as-binary-both")
./br__as-binary-left.minimal.out || tests_failed+=("br::as-binary-left")
./br__as-block-first.minimal.out || tests_failed+=("br::as-block-first")
./br__as-block-mid.minimal.out || tests_failed+=("br::as-block-mid")
./br__as-block-value-deep.minimal.out || tests_failed+=("br::as-block-value-deep")
./br__as-call_indirect-all.minimal.out || tests_failed+=("br::as-call_indirect-all")
./br__as-call_indirect-first.minimal.out || tests_failed+=("br::as-call_indirect-first")
./br__as-call_indirect-func.minimal.out || tests_failed+=("br::as-call_indirect-func")
./br__as-call_indirect-last.minimal.out || tests_failed+=("br::as-call_indirect-last")
./br__as-call_indirect-mid.minimal.out || tests_failed+=("br::as-call_indirect-mid")
./br__as-call-all.minimal.out || tests_failed+=("br::as-call-all")
./br__as-call-first.minimal.out || tests_failed+=("br::as-call-first")
./br__as-call-last.minimal.out || tests_failed+=("br::as-call-last")
./br__as-call-mid.minimal.out || tests_failed+=("br::as-call-mid")
./br__as-compare-both.minimal.out || tests_failed+=("br::as-compare-both")
./br__as-compare-left.minimal.out || tests_failed+=("br::as-compare-left")
./br__as-compare-right.minimal.out || tests_failed+=("br::as-compare-right")
./br__as-convert-operand.minimal.out || tests_failed+=("br::as-convert-operand")
./br__as-global.set-value.minimal.out || tests_failed+=("br::as-global.set-value")
./br__as-if-cond.minimal.out || tests_failed+=("br::as-if-cond")
./br__as-load-address.minimal.out || tests_failed+=("br::as-load-address")
./br__as-loadN-address.minimal.out || tests_failed+=("br::as-loadN-address")
./br__as-memory.grow-size.minimal.out || tests_failed+=("br::as-memory.grow-size")
./br__as-select-all.minimal.out || tests_failed+=("br::as-select-all")
./br__as-select-cond.minimal.out || tests_failed+=("br::as-select-cond")
./br__as-select-first.minimal.out || tests_failed+=("br::as-select-first")
./br__as-select-second.minimal.out || tests_failed+=("br::as-select-second")
./br__as-store-address.minimal.out || tests_failed+=("br::as-store-address")
./br__as-store-both.minimal.out || tests_failed+=("br::as-store-both")
./br__as-store-value.minimal.out || tests_failed+=("br::as-store-value")
./br__as-storeN-address.minimal.out || tests_failed+=("br::as-storeN-address")
./br__as-storeN-both.minimal.out || tests_failed+=("br::as-storeN-both")
./br__as-storeN-value.minimal.out || tests_failed+=("br::as-storeN-value")
./br__type-f32-f32.minimal.out || tests_failed+=("br::type-f32-f32")
./br__type-f32.minimal.out || tests_failed+=("br::type-f32")
./br__type-f64-f64.minimal.out || tests_failed+=("br::type-f64-f64")
./br__type-f64.minimal.out || tests_failed+=("br::type-f64")
./br__type-i32-i32.minimal.out || tests_failed+=("br::type-i32-i32")
./br__type-i32.minimal.out || tests_failed+=("br::type-i32")
./br__type-i32-value.minimal.out || tests_failed+=("br::type-i32-value")
./br__type-i64-i64.minimal.out || tests_failed+=("br::type-i64-i64")
./br__type-i64.minimal.out || tests_failed+=("br::type-i64")
./br__type-i64-value.minimal.out || tests_failed+=("br::type-i64-value")
./br_if__.minimal.out || tests_failed+=("br_if::*")
./br_table__.minimal.out || tests_failed+=("br_table::*")
./br_table__as-block-first.minimal.out || tests_failed+=("br_table::as-block-first")
./br_table__as-block-mid.minimal.out || tests_failed+=("br_table::as-block-mid")
./br_table__as-call-first.minimal.out || tests_failed+=("br_table::as-call-first")
./br_table__as-call_indirect-first.minimal.out || tests_failed+=("br_table::as-call_indirect-first")
./br_table__as-call_indirect-func.minimal.out || tests_failed+=("br_table::as-call_indirect-func")
./br_table__as-call_indirect-last.minimal.out || tests_failed+=("br_table::as-call_indirect-last")
./br_table__as-call_indirect-mid.minimal.out || tests_failed+=("br_table::as-call_indirect-mid")
./br_table__as-call-last.minimal.out || tests_failed+=("br_table::as-call-last")
./br_table__as-call-mid.minimal.out || tests_failed+=("br_table::as-call-mid")
./br_table__as-compare-left.minimal.out || tests_failed+=("br_table::as-compare-left")
./br_table__as-compare-right.minimal.out || tests_failed+=("br_table::as-compare-right")
./br_table__as-convert-operand.minimal.out || tests_failed+=("br_table::as-convert-operand")
./br_table__as-global.set-value.minimal.out || tests_failed+=("br_table::as-global.set-value")
./br_table__as-if-cond.minimal.out || tests_failed+=("br_table::as-if-cond")
./br_table__as-load-address.minimal.out || tests_failed+=("br_table::as-load-address")
./br_table__as-loadN-address.minimal.out || tests_failed+=("br_table::as-loadN-address")
./br_table__as-loop-first.minimal.out || tests_failed+=("br_table::as-loop-first")
./br_table__as-loop-last.minimal.out || tests_failed+=("br_table::as-loop-last")
./br_table__as-loop-mid.minimal.out || tests_failed+=("br_table::as-loop-mid")
./br_table__as-memory.grow-size.minimal.out || tests_failed+=("br_table::as-memory.grow-size")
./br_table__as-select-first.minimal.out || tests_failed+=("br_table::as-select-first")
./br_table__as-select-second.minimal.out || tests_failed+=("br_table::as-select-second")
./br_table__as-store-address.minimal.out || tests_failed+=("br_table::as-store-address")
./br_table__as-store-value.minimal.out || tests_failed+=("br_table::as-store-value")
./br_table__as-storeN-address.minimal.out || tests_failed+=("br_table::as-storeN-address")
./br_table__as-storeN-value.minimal.out || tests_failed+=("br_table::as-storeN-value")
./br_table__type-f32-value.minimal.out || tests_failed+=("br_table::type-f32-value")
./br_table__type-f32.minimal.out || tests_failed+=("br_table::type-f32")
./br_table__type-f64.minimal.out || tests_failed+=("br_table::type-f64")
./br_table__type-i32-value.minimal.out || tests_failed+=("br_table::type-i32-value")
./br_table__type-i32.minimal.out || tests_failed+=("br_table::type-i32")
./br_table__type-i64-value.minimal.out || tests_failed+=("br_table::type-i64-value")
./br_table__type-i64.minimal.out || tests_failed+=("br_table::type-i64")
# Bulk Unit Tests require various optional features
# ./bulk__data.drop.minimal.out || tests_failed+=("bulk::data.drop")
# ./bulk__elem.drop.minimal.out || tests_failed+=("bulk::elem.drop")
# ./bulk__goodbye.minimal.out || tests_failed+=("bulk::goodbye")
# ./bulk__memory.copy.minimal.out || tests_failed+=("bulk::memory.copy")
# ./bulk__memory.fill.minimal.out || tests_failed+=("bulk::memory.fill")
# ./bulk__memory.init.minimal.out || tests_failed+=("bulk::memory.init")
# ./bulk__sixtyfive.minimal.out || tests_failed+=("bulk::sixtyfive")
# ./bulk__table.copy.minimal.out || tests_failed+=("bulk::table.copy")
# ./bulk__table.init.minimal.out || tests_failed+=("bulk::table.init")
./call__.minimal.out || tests_failed+=("call::*")
./call__fib.minimal.out || tests_failed+=("call::fib")
./call_indirect__.minimal.out || tests_failed+=("call_indirect::*")
./conversions__.minimal.out || tests_failed+=("conversions::*")
./conversions__i32.reinterpret_f32.minimal.out || tests_failed+=("conversions::i32.reinterpret_f32")
./conversions__i32.trunc_f64_s.minimal.out || tests_failed+=("conversions::i32.trunc_f64_s")
./conversions__i32.trunc_f64_u.minimal.out || tests_failed+=("conversions::i32.trunc_f64_u")
./conversions__i32.trunc_f32_u.minimal.out || tests_failed+=("conversions::i32.trunc_f32_u")
./conversions__i64.extend_i32_s.minimal.out || tests_failed+=("conversions::i64.extend_i32_s")
./conversions__i64.extend_i32_u.minimal.out || tests_failed+=("conversions::i64.extend_i32_u")
./loop__.minimal.out || tests_failed+=("loop::*")
./if__.minimal.out || tests_failed+=("if::*")
./if__as-unary-operand.minimal.out || tests_failed+=("if::as-unary-operand.minimal")
./return__.minimal.out || tests_failed+=("return::*")
./select__.minimal.out || tests_failed+=("select::*")
./switch__.minimal.out || tests_failed+=("switch::*")
./unwind__.minimal.out || tests_failed+=("unwind::*")
./unwind__by-br_if-value.minimal.out || tests_failed+=("unwind::by-br_if-value")

for test_failed in "${tests_failed[@]}"; do
	echo "Failed $test_failed"
done

if ((${#test_failed} == 0)); then
	echo "Passed all tests!"
	exit 0
else
	exit 1
fi
